/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rob.view;

import com.rob.utilidades.Utils;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Roberto Esteban
 */
public class DialogGitHub extends javax.swing.JDialog {

    private GUIMenu menuGUI;
    
    public DialogGitHub(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.menuGUI = (GUIMenu) parent;
        initComponents();
        setFrame();
        setPanelRepo();
    }
    
    private void setFrame() {
        this.setLocationRelativeTo(menuGUI);
        this.getContentPane().setBackground(Utils.COLOR_FONDO_APP);
        this.labelTitulo.setForeground(Color.BLACK);
        this.labelTitulo.setFont(new Font("Gagalin", Font.PLAIN, 36));
    }
    
    private void setPanelRepo() {
        this.panelRepo.setBackground(Utils.COLOR_FONDO_APP);
        //Configuro los componentes
        this.cajaRepo.setText("https://github.com/r0b3rt023/Multiply");
        this.cajaRepo.setEditable(false);
        this.cajaRepo.setFont(new Font("Ebrina", Font.BOLD, 16));
        
        this.botonCopiar.setText("COPIAR");
        this.botonCopiar.setFont(new Font("Ebrina", Font.BOLD, 16));
        this.botonCopiar.setBackground(Utils.COLOR_BOTONES_OPCIONES);
        this.botonCopiar.setFocusPainted(false);
        this.botonCopiar.addActionListener(menuGUI.getMenuController());
        
        this.labelCopiado.setText("");
        this.labelCopiado.setFont(new Font("Ebrina", Font.BOLD, 22));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        panelRepo = new javax.swing.JPanel();
        cajaRepo = new javax.swing.JTextField();
        botonCopiar = new javax.swing.JButton();
        labelCopiado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("GIT HUB REPO");

        panelRepo.setLayout(new java.awt.BorderLayout(20, 35));
        panelRepo.add(cajaRepo, java.awt.BorderLayout.CENTER);

        botonCopiar.setText("Copiar");
        panelRepo.add(botonCopiar, java.awt.BorderLayout.LINE_END);

        labelCopiado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCopiado.setText("aaaa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 60, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCopiado, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelRepo, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addComponent(panelRepo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(labelCopiado)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBotonCopiar() {
        return botonCopiar;
    }

    public String getTextoCajaRepo() {
        return cajaRepo.getText();
    }

    public void setTextoLabelCopiado(String texto) {
        this.labelCopiado.setText(texto);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCopiar;
    private javax.swing.JTextField cajaRepo;
    private javax.swing.JLabel labelCopiado;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelRepo;
    // End of variables declaration//GEN-END:variables
}
