/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rob.view;

import com.rob.utilidades.Utils;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JSlider;
import javax.swing.JToggleButton;

/**
 *
 * @author Roberto Esteban
 */
public class DialogConfiguracion extends javax.swing.JDialog {

    private GUIMenu menuGUI;
    
    public DialogConfiguracion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.menuGUI = (GUIMenu) parent;
        initComponents();
        setFrame();
    }
    
    private void setFrame() {
        this.getContentPane().setBackground(Utils.COLOR_FONDO_APP);
        this.labelTitulo.setForeground(Utils.COLOR_TEXTO_BOTONES);
        this.labelTitulo.setFont(new Font("Gagalin", Font.PLAIN, 36));
        this.setLocationRelativeTo(menuGUI);
        this.setTitle("CONFIGURACIÓN");
        
        setPanelSonido();
        setPanelMultiplicaciones();
        
        this.pack();
    }
    
    private void setPanelSonido() {
        this.panelSonido.setBackground(Utils.COLOR_BOTONES_OPCIONES_HOVER);
        //Configuro los componentes del panel
        this.botonSonido.setIcon(new ImageIcon(getClass().getResource(Utils.ICONO_SONIDO_ON)));
        this.botonSonido.setText("");
        this.botonSonido.setBorderPainted(false);
        this.botonSonido.setFocusPainted(false);
        this.botonSonido.setContentAreaFilled(false);
        this.botonSonido.setSelected(true);
        this.botonSonido.addItemListener(menuGUI.getMenuController());
    }
    
    private void setPanelMultiplicaciones() {
        this.panelMultiplicaciones.setBackground(Utils.COLOR_BOTONES_OPCIONES_HOVER);
        //Configuro los componentes del panel
        this.sliderNumMult.setMinimum(5);
        this.sliderNumMult.setMaximum(25);
        this.sliderNumMult.setValue(Utils.NUMERO_MULTIPLIACIONES);
        this.sliderNumMult.setPaintLabels(true);
        this.sliderNumMult.addChangeListener(menuGUI.getMenuController());
        this.sliderNumMult.setBackground(Utils.COLOR_BOTONES_OPCIONES_HOVER);
        
        this.labelMultiplicaciones.setText(String.valueOf(Utils.NUMERO_MULTIPLIACIONES));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        panelMultiplicaciones = new javax.swing.JPanel();
        sliderNumMult = new javax.swing.JSlider();
        labelMultiplicaciones = new javax.swing.JLabel();
        panelSonido = new javax.swing.JPanel();
        botonSonido = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("CONFIGURACIÓN");

        panelMultiplicaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nº de multiplicaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Ebrima", 1, 20))); // NOI18N

        labelMultiplicaciones.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        labelMultiplicaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMultiplicaciones.setText("jLabel1");

        javax.swing.GroupLayout panelMultiplicacionesLayout = new javax.swing.GroupLayout(panelMultiplicaciones);
        panelMultiplicaciones.setLayout(panelMultiplicacionesLayout);
        panelMultiplicacionesLayout.setHorizontalGroup(
            panelMultiplicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMultiplicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMultiplicacionesLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(sliderNumMult, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelMultiplicacionesLayout.setVerticalGroup(
            panelMultiplicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMultiplicacionesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(sliderNumMult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMultiplicaciones)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelSonido.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Sonido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Ebrima", 1, 20))); // NOI18N

        javax.swing.GroupLayout panelSonidoLayout = new javax.swing.GroupLayout(panelSonido);
        panelSonido.setLayout(panelSonidoLayout);
        panelSonidoLayout.setHorizontalGroup(
            panelSonidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSonidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSonido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSonidoLayout.setVerticalGroup(
            panelSonidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSonidoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(botonSonido)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelMultiplicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelSonido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(panelSonido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(panelMultiplicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setNumMultiplicaciones(Integer num) {
        this.labelMultiplicaciones.setText(String.valueOf(num));
    }

    public JSlider getSliderNumMult() {
        return sliderNumMult;
    }

    public JToggleButton getBotonSonido() {
        return botonSonido;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonSonido;
    private javax.swing.JLabel labelMultiplicaciones;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelMultiplicaciones;
    private javax.swing.JPanel panelSonido;
    private javax.swing.JSlider sliderNumMult;
    // End of variables declaration//GEN-END:variables
}
