package com.rob.view;

import com.rob.utilidades.Utils;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Roberto Esteban
 */
public class DialogPuntuacion extends javax.swing.JDialog {

    private final GUIJuego juegoGUI;
    
    private final Integer puntuacion;
    
    /**
     * Creates new form DialogPuntuacion
     */
    public DialogPuntuacion(java.awt.Frame parent, boolean modal, int puntuacion) {
        super(parent, modal);
        this.juegoGUI = (GUIJuego) parent;
        this.puntuacion = puntuacion;
        initComponents();
        setFrame();
    }
    
    private void setFrame() {
        this.getContentPane().setBackground(Utils.COLOR_FONDO_APP);
        //Configuro sus componentes
        setPanelPuntuacion();
        this.setLocationRelativeTo(juegoGUI);
        this.pack();
    }
    
    private void setPanelPuntuacion() {
        this.panelPuntuacion.setBackground(Utils.COLOR_BOTONES_OPCIONES);
        //Configuro sus componentes
        this.labelTitulo.setFont(new Font("Gagalin", Font.BOLD, 35));
        this.labelTitulo.setForeground(Color.BLACK);
        
        this.labelTextoPuntuacion.setFont(new Font("Ebrima", Font.BOLD, 22));
        this.labelTextoPuntuacion.setForeground(Color.BLACK);
        
        this.labelPuntuacion.setText("Puntuación: " + puntuacion + " puntos");
        this.labelPuntuacion.setFont(new Font("Ebrima", Font.BOLD, 22));
        this.labelPuntuacion.setForeground(Color.BLACK);
        //Configuro los botones
        this.botonMenu.setText("Volver al menú");
        this.botonMenu.setBackground(Color.WHITE);
        this.botonMenu.setFocusPainted(false);
        this.botonMenu.setFont(new Font("Ebrima", Font.BOLD, 17));
        this.botonMenu.addActionListener(juegoGUI.getJuegoController());
        this.botonVolverJugar.setText("Jugar de nuevo");
        this.botonVolverJugar.setBackground(Color.WHITE);
        this.botonVolverJugar.setFocusPainted(false);
        this.botonVolverJugar.setFont(new Font("Ebrima", Font.BOLD, 17));
        this.botonVolverJugar.addActionListener(juegoGUI.getJuegoController());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        panelPuntuacion = new javax.swing.JPanel();
        labelTextoPuntuacion = new javax.swing.JLabel();
        labelPuntuacion = new javax.swing.JLabel();
        botonMenu = new javax.swing.JButton();
        botonVolverJugar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("PUNTUACIÓN");

        panelPuntuacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelTextoPuntuacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTextoPuntuacion.setText("jLabel1");

        labelPuntuacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPuntuacion.setText("jLabel1");

        botonMenu.setText("jButton2");

        botonVolverJugar.setText("jButton1");

        javax.swing.GroupLayout panelPuntuacionLayout = new javax.swing.GroupLayout(panelPuntuacion);
        panelPuntuacion.setLayout(panelPuntuacionLayout);
        panelPuntuacionLayout.setHorizontalGroup(
            panelPuntuacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntuacionLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(botonVolverJugar)
                .addGap(30, 30, 30)
                .addComponent(botonMenu)
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(panelPuntuacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPuntuacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPuntuacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTextoPuntuacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPuntuacionLayout.setVerticalGroup(
            panelPuntuacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntuacionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelTextoPuntuacion)
                .addGap(27, 27, 27)
                .addComponent(labelPuntuacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(panelPuntuacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVolverJugar)
                    .addComponent(botonMenu))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(panelPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addGap(58, 58, 58)
                .addComponent(panelPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setLabelTextoPuntuacion(String textoPuntuacion) {
        this.labelTextoPuntuacion.setText(textoPuntuacion);
    }

    public JButton getBotonMenu() {
        return botonMenu;
    }

    public JButton getBotonVolverJugar() {
        return botonVolverJugar;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMenu;
    private javax.swing.JButton botonVolverJugar;
    private javax.swing.JLabel labelPuntuacion;
    private javax.swing.JLabel labelTextoPuntuacion;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelPuntuacion;
    // End of variables declaration//GEN-END:variables
}
